services:
  postgres:
    container_name: auth-postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=exercise
    ports:
      - 8050:5432
    image: postgres:18.4-alpine3.22
  redis:
    container_name: auth-redis
    environment:
      - REDIS_ARGS=--requirepass password --appendonly yes
    image: redis:8.8.0
    ports:
      - 8051:6379
    command: redis server --port 6379
